namespace: hetzner
name: hcloud
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  ansible.netcommon: '>=0.1.0'
repository: git@github.com:ansible-collection-migration/hetzner.hcloud.git
documentation: https://github.com/ansible-collection-migration/hetzner.hcloud/tree/master/docs
homepage: https://github.com/ansible-collection-migration/hetzner.hcloud
issues: https://github.com/ansible-collection-migration/hetzner.hcloud/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
