namespace: hetzner
name: hcloud
version: 0.1.0
readme: README.md
authors:
  - Lukas Kaemmerling (github.com/LKaemmerling)
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  ansible.netcommon: '>=0.0.1'
repository: https://github.com:ansible-collections/hetzner.hcloud
documentation: https://github.com:ansible-collections/hetzner.hcloud/tree/master/docs
homepage: https://github.com:ansible-collections/hetzner.hcloud
issues: https://github.com:ansible-collections/hetzner.hcloud/issues
